---
- block:
    - name: Install SCL package
      package:
        name: 'centos-release-scl'
        state: present
      when: ansible_distribution == 'CentOS'

    - name: Set listen addresses
      set_fact:
        postgresql_global_config_options:
          - option: listen_addresses
            value: "*"
      when: pulp_settings.databases.default.HOST != 'localhost'

    - name: Install and configure PostgreSQL
      import_role:
        name: geerlingguy.postgresql
  become: yes
