---
- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
    daemon_reload: true
  become: true

- name: reload apache
  systemd:
    name: "{{ pulp_webserver_apache_service }}"
    state: reloaded
    daemon_reload: true
  become: true

- name: update ca trust
  command: "{{ pulp_webserver_trusted_root_certificates_update_bin }}"
  become: true
