---
galaxy_info:
  author: Pulp Team
  description: A role that sets up a development environment for Pulp 3, and its plugins
  issue_tracker_url: https://github.com/pulp/pulp_installer/issues/new
  license: GPL-2.0-or-later
  company: Red Hat
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - bullseye
    - name: Fedora
      versions:
        - 32
        - 33
        - 34
    - name: EL
      versions:
        - 7
        - 8
  galaxy_tags:
    - pulp
    - pulpcore
dependencies:
  - pulp_common
collections:
  - community.general
