---
# Molecule runs tests in containers.
sudo: required
# By default, Traivs provides Ubuntu 14.04 VMs. We specify a newer release so
# that Python 3.7 can be used in testing.
dist: bionic
services:
  - docker

# Manually defining a build matrix is more cumbersome than using a tool like
# tox-travis. However, this avoids adding yet another layer of abstraction, and
# it offers great flexibility. See:
# https://stackoverflow.com/questions/37016688/how-to-run-tox-with-travis-ci
language: python
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.6
      env: TOXENV=py36-default
    - python: 3.6
      env: TOXENV=py36-upgrade
    - python: 3.7
      env: TOXENV=py37
before_install:
  - docker pull quay.io/pulp/pulp-ci-c7:3.0.0
  - docker pull quay.io/pulp/pulp-ci-dbuster:3.0.0
  - docker pull quay.io/pulp/pulp-ci-f31:3.0.0
  - .travis/before_install.sh
  # Created template_config.yml with plugin_template,
  # and after that I removed manually travis files not related to validating commit
  # also removed some python related stuff like flake8, black and pip installing doc/test requirements
install:
  - pip install --upgrade pip
  - pip install tox
  # Much easier than trying to use the travis_wait bash function in tox.
  - wget -qO- https://github.com/crazy-max/travis-wait-enhanced/releases/download/v1.0.0/travis-wait-enhanced_1.0.0_linux_x86_64.tar.gz | sudo tar -C /usr/local/bin -zxvf - travis-wait-enhanced
script:
  - TRAVIS_WAIT="travis-wait-enhanced --timeout=20m --" tox
