---

language: python
python: 2.7

sudo: required

# Enable the docker service
services:
  - docker

before_install:
  - sudo apt-get -qq update

# Install molecule and docker-py
install:
  - pip install tox-travis

# Test all the scenarios against the Ansible versions defined in the tox.ini file
script:
  - tox -e standards
  - tox

