---
# Options
pulp_devel_supplement_bashrc: true
pulp_default_admin_password: password
pulp_api_bind: "unix:/var/run/pulpcore-api/pulpcore-api.sock"
pulp_content_bind: "unix:/var/run/pulpcore-content/pulpcore-content.sock"
pulp_install_plugins:
  # galaxy-ng:
  #   source_dir: "/home/vagrant/devel/galaxy_ng"
  # pulp-2to3-migration:
  #   source_dir: "/home/vagrant/devel/pulp-2to3-migration"
  # pulp-ansible:
  #   source_dir: "/home/vagrant/devel/pulp_ansible"
  # pulp-certguard:
  #   source_dir: "/home/vagrant/devel/pulp-certguard"
  # pulp-container:
  #   source_dir: "/home/vagrant/devel/pulp_container"
  # pulp-cookbook:
  #   source_dir: "/home/vagrant/devel/pulp_cookbook"
  # pulp-deb:
  #   source_dir: "/home/vagrant/devel/pulp_deb"
  pulp-file:
    source_dir: "/home/vagrant/devel/pulp_file"
  # pulp-gem:
  #   source_dir: "/home/vagrant/devel/pulp_gem"
  # pulp-maven:
  #   source_dir: "/home/vagrant/devel/pulp_maven"
  # pulp-npm:
  #   source_dir: "/home/vagrant/devel/pulp_npm"
  # pulp-python:
  #   source_dir: "/home/vagrant/devel/pulp_python"
  # pulp-rpm:
  #   source_dir: "/home/vagrant/devel/pulp_rpm"

# Vagrant source install Required
pulp_user: "vagrant"
developer_user: "vagrant"
developer_user_home: "/home/vagrant"
pulp_source_dir: "/home/vagrant/devel/pulpcore"

# # Uncomment to prevent https configuration
# pulp_webserver_disable_https: true

# # Uncomment to deploy with apache instead of nginx
# pulp_webserver_server: "apache"

pulp_settings:
  secret_key: "unsafe_default"
  content_origin: "{{ pulp_webserver_disable_https | default(false) | ternary('http', 'https') }}://{{ ansible_fqdn }}"
  allowed_export_paths: ["/tmp"]
  allowed_import_paths: ["/tmp"]
...
