---
pulp_default_admin_password: password
pulp_install_plugins:
  # galaxy-ng: {}
  # pulp-2to3-migration: {}
  # pulp-ansible: {}
  # pulp-certguard: {}
  # pulp-cookbook: {}
  # pulp-deb: {}
  # pulp-container: {}
  pulp-file: {}
  # pulp-gem: {}
  # pulp-maven: {}
  # pulp-python: {}
  # pulp-rpm: {}

# # Uncomment to prevent https configuration
# pulp_webserver_disable_https: true

# # Uncomment to deploy with apache instead of nginx
# pulp_webserver_server: "apache"

pulp_settings:
  secret_key: "unsafe_default"
  content_origin: "{{ pulp_webserver_disable_https | default(false) | ternary('http', 'https') }}://{{ ansible_fqdn }}"
  # # Uncomment to allow using the pulp export feature
  # allowed_export_paths: ["/tmp"]
  # allowed_import_paths: ["/tmp"]
...
