---
pulp_default_admin_password: password
pulp_install_plugins:
  # pulp-ansible: {}
  # galaxy-ng: {}
  # pulp-certguard: {}
  # pulp-cookbook: {}
  # pulp-deb: {}
  # pulp-container: {}
  # pulp-gem: {}
  # pulp-maven: {}
  # pulp-python: {}
  # pulp-rpm: {}
  pulp-file: {}

# # Uncomment to prevent https configuration
# pulp_webserver_disable_https: true

pulp_settings:
  secret_key: "unsafe_default"
  content_origin: "{{ pulp_webserver_disable_https | default(false) | ternary('http', 'https') }}://{{ ansible_fqdn }}"
...
