---
site_name: Pulp Installer
site_description: Pulp 3 Ansible Installer
site_author: Pulp Team
site_url: https://docs.pulpproject.org/pulp_installer/
repo_name: pulp/pulp_installer
repo_url: https://github.com/pulp/pulp_installer
theme:
  features:
    - search.suggest
    - search.highlight
    - search.share
  name: material
  logo: images/pulp_logo_big.png
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: white
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: white
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
nav:
  - Home: index.md
  - Getting started: quickstart.md
  - Customizing Your Pulp Deployment: customizing.md
  - clustering.md
  - upgrades.md
  - troubleshooting.md
  - Object Storage: objectstorage.md
  - Let's Encrypt: letsencrypt.md
  - contributing.md
  - pulplift.md
  - Changelog: CHANGES.md
  - Roles:
      - Pulp Common: roles/pulp_common.md
      - Pulp API: roles/pulp_api.md
      - Pulp Content: roles/pulp_content.md
      - Pulp Database: roles/pulp_database.md
      - Pulp Database Configuration: roles/pulp_database_config.md
      - Pulp Devel: roles/pulp_devel.md
      - Pulp Redis: roles/pulp_redis.md
      - Pulp Webserver: roles/pulp_webserver.md
      - Pulp Workers: roles/pulp_workers.md
      - Pulp Health Check: roles/pulp_health_check.md
  - Helper Roles for Pulp Common:
      - Galaxy NG post-install: helper_roles/galaxy_post_install.md
      - Pulp RPM prerequisites: helper_roles/pulp_rpm_prerequisites.md
      - Pulp Repos: helper_roles/pulp_repos.md
  - Meta Roles:
      - Pulp All Services: meta_roles/pulp_all_services.md
      - Pulp Services: meta_roles/pulp_services.md
markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.superfences
  - admonition
extra:
  version:
    provider: mike
    default: latest
plugins:
  - git-revision-date
  - search:
      lang: en
      prebuild_index: true
