---
galaxy_info:
  author: Pulp
  description: Pulp Web Server
  company: Red Hat
  min_ansible_version: 2.4
  platforms:
    - name: Fedora
      versions:
        - 28
  license: GPL-3.0
dependencies:
  - role: pulp3
