---
galaxy_info:
  author: Pulp
  description: Pulp Resource Manager
  company: Red Hat
  min_ansible_version: 2.4
  platforms:
    - name: Debian
      versions:
        - buster
    - name: Fedora
      versions:
        - 29
        - 30
  license: GPL-3.0

# Depend on pulp-redis for RQ.
dependencies:
  - role: pulp-redis
