---

pulp_cache_dir: '/var/lib/pulp/tmp'
pulp_config_dir: '/etc/pulp'
pulp_db_type: 'postgres'
pulp_default_admin_password: ''
pulp_install_dir: '/usr/local/lib/pulp'
pulp_install_plugins: {}
pulp_install_api_service: true
pulp_user: pulp
pulp_user_home: '/var/lib/pulp'
pulp_pip_editable: yes
pulp_api_host: localhost
pulp_api_port: 24817
