---
# vars needed for 'rh-postgresql10' SCL
postgresql_version: "10"
postgresql_daemon: postgresql-10
postgresql_packages:
  - postgresql10
  - postgresql10-server
  - postgresql10-libs
  - postgresql10-contrib
postgresql_bin_path: /usr/pgsql-10/bin
postgresql_data_dir: /var/lib/pgsql/10/data
postgresql_config_path: /var/lib/pgsql/10/data
