---
galaxy_info:
  author: Pulp Team
  description: A role to install all Pulp services (first-party & third-party) on a single host.
  issue_tracker_url: https://github.com/pulp/pulp_installer/issues/new
  license: GPL-2.0-or-later
  company: Red Hat
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - bullseye
    - name: EL
      versions:
        - "7"
        - "8"
    - name: Fedora
      versions:
        - "33"
        - "34"
        - "35"
  galaxy_tags:
    - pulp
    - pulpcore
dependencies:
  - role: pulp_database
  - role: pulp_redis
  - role: pulp_services
  - role: pulp_health_check
  - role: pulp_webserver
# When dynamically including roles,  it only installs the collection dependencies
# for the role that you explicitly specify.
collections:
  - ansible.posix  # dependency for pulp_webserver
  - community.crypto  # dependency for pulp_webserver
  - community.postgresql   # dependency for pulp_database
