---

pulp_user: pulp

pulp_install_dir: '/opt/pulp'
pulp_install_plugins: []
pulp_install_prerequisites: true

pulp_database_migrate: true
pulp_default_admin_password: ''

pulp_config_dir: '/etc/pulp'
pulp_var_dir: '/var/lib/pulp'
pulp_cache_dir: '/var/cache/pulp'

pulp_postgres_user: 'postgres'
pulp_postgres_login_user: ''
pulp_postgres_login_password: ''
pulp_postgres_port: 5432

pulp_config_database:
  default:
    ENGINE: django.db.backends.sqlite3
    NAME: '{{ pulp_var_dir }}/database/pulp.sqlite3'

pulp_config_secret_key: ''
pulp_config: {}

pulp_install_service_files: true

pulp_resource_manager_state: started
pulp_resource_manager_enabled: true

pulp_wsgi_state: started
pulp_wsgi_enabled: true
