---
pulp_install_postgresql: true
pulp_postgresql_host: localhost
pulp_postgresql_database: pulp
pulp_postgresql_user: pulp
pulp_postgresql_password: pulp
pulp_database_config:
  default:
    HOST: "{{ pulp_postgresql_host }}"
    ENGINE: django.db.backends.postgresql_psycopg2
    NAME: "{{ pulp_postgresql_database }}"
    USER: "{{ pulp_postgresql_user }}"
    PASSWORD: "{{ pulp_postgresql_password }}"
