---
galaxy_info:
  author: Pulp Team
  description: Support role to install the prerequisites for pulp_rpm
  company: Red Hat
  issue_tracker_url: https://pulp.plan.io/projects/pulp_rpm/issues
  license: GPL-2.0-or-later
  min_ansible_version: 2.8
  #
  # Provide a list of supported platforms, and for each platform a list of versions.
  # If you don't wish to enumerate all versions for a particular platform, use 'all'.
  # To view available platforms and versions (or releases), visit:
  # https://galaxy.ansible.com/api/v1/platforms/
  #
  platforms:
    - name: Fedora
      versions:
        - 30
        - 31
    - name: EL
      versions:
        - 7
        - 8
  galaxy_tags:
    - pulp
    - pulpcore
dependencies: []
# List your role dependencies here, one per line. Be sure to remove the '[]' above,
# if you add dependencies to this list.
