---
- name: Load OS specific variables
  include_vars: '{{ ansible_distribution }}.yml'
  tags:
    - always

- name: Add redis repository
  apt_repository:
    repo: ppa:chris-lea/redis-server
    update_cache: yes
  become: yes
  when: ansible_distribution == 'Ubuntu'

- block:

    - name: Install requirements
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{ pulp_preq_packages }}"

    - name: Install Redis
      package:
        name: redis
        state: present

    - name: Start Redis
      systemd:
        name: "{{ pulp_redis_server_name }}"
        state: started
        enabled: yes
        daemon_reload: yes

  become: true
