---
# Variables used by the ANXS Postgresql role

postgresql_databases:
    - name: '{{ pulp_database_config["default"]["NAME"] }}'
      owner: '{{ pulp_database_config["default"]["NAME"] }}'

postgresql_users:
    - name: '{{ pulp_database_config["default"]["NAME"] }}'

postgresql_user_privileges:
    - name: '{{ pulp_database_config["default"]["NAME"] }}'
      db: '{{ pulp_database_config["default"]["NAME"] }}'
      priv: ALL
      role_attr_flags: LOGIN

postgresql_version: '9.6'
