---
- name: Load OS specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_major_version }}.yml'
        - '{{ ansible_facts.distribution }}.yml'
        - '{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml'
        - '{{ ansible_facts.os_family }}.yml'
      paths:
        - 'vars'
  tags:
    - always

- name: include_tasks to build Galaxy WebUI if galaxy-ng is among the plugins
  include_tasks:
    file: galaxy_ui.yml
    apply:
      become: true
  when: pulp_install_plugins_normalized['galaxy-ng'] is defined

- import_tasks: install_basic_packages.yml
  become: true

- name: "Add {{ pulp_user }} to systemd-journal group"
  user:
    name: "{{ pulp_user }}"
    groups: systemd-journal
    append: yes
  become: true

- import_tasks: install_podman.yml
  become: true
  when: pulp_devel_install_podman

- import_tasks: install_docs_requirements.yml
  become: true
  become_user: '{{ pulp_user }}'

- name: Include bashrc
  include_tasks:
    file: bashrc.yml
    apply:
      become: true
      become_user: "{{ developer_user }}"

- import_tasks: config_files.yml
  become: true
  become_user: "{{ developer_user }}"

- name: Trusting Pulp CA
  shell: |
    set -o pipefail
    CERTIFI=$({{ pulp_install_dir }}/bin/python -c 'import certifi; print(certifi.where())')
    cat {{ pulp_certs_dir }}/root.crt | tee -a $CERTIFI
    CERT=$({{ pulp_install_dir }}/bin/python -c 'import ssl; print(ssl.get_default_verify_paths().openssl_cafile)')
    cat $CERTIFI | tee -a $CERT
  args:
    # Debian defaults to bourne, but it doesn't understand pipefail.
    executable: /bin/bash
  changed_when: false
  check_mode: false
  become: yes

- import_tasks: pulp_cli.yml
  become: true
  become_user: "{{ developer_user }}"

- name: Set crypto policy for Fedora (to allow using CDN certificates)
  become: true
  command: update-crypto-policies --set LEGACY
  when:
    - ansible_facts.distribution == "Fedora"
  tags:
    - molecule-idempotence-notest

- name: Set the message of the day
  copy:
    src: motd
    dest: /etc/motd
    mode: '0644'
  become: true

- name: Check SELinux logs
  stat:
    path: "/var/log/audit/audit.log"
  register: selinuxlog
  become: true

- name: SELinux Analyze
  shell: |
    set -o pipefail
    sealert --analyze=/var/log/audit/audit.log | grep "SELinux is preventing"
  args:
    # Debian defaults to bourne, but it doesn't understand pipefail.
    executable: /bin/bash
  changed_when: false
  register: selinux_analyze
  check_mode: false
  become: true
  when:
    - selinuxlog.stat.exists
    - ansible_facts.os_family == "RedHat"

- name: SELinux status
  debug:
    var: selinux_analyze.stdout_lines
  when:
    - ansible_facts.os_family == "RedHat"
    - selinuxlog.stat.exists
    - selinux_analyze.stdout
...
