---
pulp_preq_packages:
  - python36
  - python36-devel
  - python-setuptools
  - libselinux-python  # For ansible itself
  - python-psycopg2
  - python-contextlib2
pulp_python_interpreter: /usr/bin/python36
