---
- block:

    - name: Install Apache
      package:
        name: "{{ pulp_webserver_apache_package }}"
        state: present

    - name: Install Apache vhost file
      template:
        src: pulp-vhost.conf.j2
        dest: "{{ pulp_webserver_apache_vhost_dir }}/pulp-vhost.conf"
        mode: '0600'
      notify: reload apache

    - name: Enable Apache vhost files and mod files
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop:
        - src: ../sites-available/pulp-vhost.conf
          dest: /etc/apache2/sites-enabled/pulp-vhost.conf
        - src: ../mods-available/proxy.load
          dest: /etc/apache2/mods-enabled/proxy.load
      when: ansible_facts.os_family == "Debian"
      notify: reload apache

    - name: Create directory for Pulp Apache snippets
      file:
        path: "{{ pulp_webserver_apache_snippets_dir }}"
        mode: '0600'
        state: directory

    # FIXME: The ansible output here over the results is very ugly.
    # It may be a lot cleaner if we were to use the command module,
    # above and/or create a temporary data structure.
    - name: Symlink Apache snippets
      file:
        src: "{{ item.stdout_lines | last }}"
        # Note: item.item is pulp_install_plugins_normalized
        dest: "{{ pulp_webserver_apache_snippets_dir }}/{{ item.item.key | regex_replace('-', '_') }}.conf"
        state: link
      loop: '{{ snippets.results }}'
      when: item.rc == 0
      notify: reload apache

    - name: Start and enable Apache
      systemd:
        name: "{{ pulp_webserver_apache_service }}"
        state: started
        enabled: true
        daemon_reload: true

  become: true
