---
- block:

    - name: Install firewalld
      package:
        name: firewalld
        state: present

    - name: Install firewalld dependencies if exist
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{ pulp_firewall_dependencies }}"
      when: pulp_firewall_dependencies is defined

    - name: Start and enable firewalld
      systemd:
        name: firewalld
        state: started
        enabled: true

    - name: Accept connections on port 80
      firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled

    - name: Accept connections on port 443
      firewalld:
        service: https
        permanent: true
        immediate: true
        state: enabled
      when: not pulp_webserver_disable_https | bool

  become: true
