---
- name: Import specified TLS certificate
  copy:
    src: "{{ pulp_webserver_tls_cert }}"
    dest: "{{ pulp_certs_dir }}/pulp_webserver.crt"
    owner: root
    group: "{{ pulp_group }}"
    mode: 0600
    remote_src: "{{ pulp_webserver_tls_files_remote }}"
  notify: reload {{ pulp_webserver_server }}

- name: Import specified TLS private key
  copy:
    src: "{{ pulp_webserver_tls_key }}"
    dest: "{{ pulp_certs_dir }}/pulp_webserver.key"
    owner: root
    group: "{{ pulp_group }}"
    mode: 0600
    remote_src: "{{ pulp_webserver_tls_files_remote }}"
  notify: reload {{ pulp_webserver_server }}
