---
- name: Install several useful packages (distro-agnostic)
  package:
    name:
      - dstat
      - git
      - htop
      - iotop
      - jq
      - ncdu
      - tmux
      - tree
      - wget
      - curl
      - gnupg
      - rubygems
    state: present
  retries: "{{ pulp_devel_package_retries }}"
  register: result
  until: result is succeeded

- name: Install several useful packages (CentOS 7 specific)
  package:
    name:
      - nc
      - python-virtualenvwrapper
      - ruby-devel
      - jnettop
      - fd-find
      - fzf
    state: present
  retries: "{{ pulp_devel_package_retries }}"
  register: result
  until: result is succeeded
  when:
    - (ansible_distribution == 'CentOS') or (ansible_distribution == 'RedHat')
    - ansible_distribution_major_version|int == 7

- name: Install several useful packages (CentOS 8 specific)
  package:
    name:
      - bash-completion
      - dnf-utils
      - nc
      - python-django-bash-completion
      - python3-setuptools
      - vim-enhanced
      - ruby-devel
      # Until packaged for EPEL8
      - "https://archives.fedoraproject.org/pub/archive/fedora/linux/releases/\
      28/Everything/x86_64/os/Packages/p/\
      python3-virtualenvwrapper-4.8.2-4.fc28.noarch.rpm"
      - "https://archives.fedoraproject.org/pub/archive/fedora/linux/releases/\
      28/Everything/x86_64/os/Packages/p/\
      python3-virtualenv-clone-0.2.6-9.fc28.noarch.rpm"
      - "https://archives.fedoraproject.org/pub/archive/fedora/linux/releases/\
      28/Everything/x86_64/os/Packages/p/\
      python3-stevedore-1.25.0-2.fc28.noarch.rpm"
    state: present
  retries: "{{ pulp_devel_package_retries }}"
  register: result
  until: result is succeeded
  when:
    - (ansible_distribution == 'CentOS') or (ansible_distribution == 'RedHat')
    - ansible_distribution_major_version|int == 8

- name: Create virtualenvwrapper symlink
  file:
    src: /usr/bin/virtualenvwrapper-3.sh
    dest: /usr/bin/virtualenvwrapper.sh
    state: link
  when:
    - (ansible_distribution == 'CentOS') or (ansible_distribution == 'RedHat')
    - ansible_distribution_major_version|int == 8

- name: Install several useful packages (Debian-specific)
  package:
    name:
      - bash-completion
      - fd-find
      - fzf
      - netcat
      - python3-setuptools
      - virtualenvwrapper
      - ripgrep
      - vim
      - software-properties-common
      - ruby-dev
      - jnettop
    state: present
  retries: "{{ pulp_devel_package_retries }}"
  register: result
  until: result is succeeded
  when: ansible_distribution == 'Debian'

- name: Install several useful packages (Fedora-specific)
  package:
    name:
      - bash-completion
      - dnf-utils
      - fd-find
      - fzf
      - nc
      - python-django-bash-completion
      - python3-setuptools
      - python3-virtualenvwrapper
      - ripgrep
      - vim-enhanced
      - ruby-devel
      - jnettop
    state: present
  retries: "{{ pulp_devel_package_retries }}"
  register: result
  until: result is succeeded
  when: ansible_distribution == 'Fedora'

- name: Install Minio Client
  get_url:
    url: https://dl.min.io/client/mc/release/linux-amd64/mc
    dest: /usr/local/bin
    owner: '{{ developer_user }}'
    mode: 0750
...
