---

pulp_cache_dir: '/var/lib/pulp/tmp'
pulp_config_dir: '/etc/pulp'
# This var intentionally not advertised to users, because there is no
# foreseeable need for them to change the filename, only pulp_config_dir.
pulp_settings_file: '{{ pulp_config_dir }}/settings.py'
# Users should not set this variable, instead using `pulp_settings.databases`
pulp_settings_db_defaults:
  databases:
    default:
      HOST: localhost
      ENGINE: django.db.backends.postgresql_psycopg2
      NAME: pulp
      USER: pulp
      PASSWORD: pulp
pulp_install_source: pip
pulp_install_dir: '{{ (pulp_install_source == "packages") | ternary("/usr", "/usr/local/lib/pulp") }}'
pulp_install_api_service: true
# Deprecated unused. Variables for dependency upgrades are TBD
pulp_upgrade: false
#  Intentionally not advertised to users. They should not set this unless
#  they are confident that this version of pulp_installer is compatible with
#  pulp_version.
#  Ignored if pulp_source_dir is set
pulp_version: "3.4.1"
pulp_user: pulp
pulp_user_id:
pulp_group: pulp
pulp_group_id:
pulp_user_home: '/var/lib/pulp'
pulp_pip_editable: yes
pulp_use_system_wide_pkgs: false
prereq_pip_packages: []
pulp_rhel_codeready_repo:
  - codeready-builder-for-rhel-8-x86_64-rpms
  - rhui-codeready-builder-for-rhel-8-rhui-rpms
  - codeready-builder-for-rhel-8-rhui-rpms
rhel7_optional_repo:
  - rhui-rhel-7-server-rhui-optional-rpms
  - rhel-7-server-rhui-optional-rpms
  - rhel-7-server-optional-rpms
  - rhel-7-workstation-optional-rpms
epel_release_packages:
  - epel-release
  - "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
# The names of any pip packages that are plugins but do not begin with "pulp-"
# These are specified regardless of whether or not the user is installing it.
# We will advertise this to users once we feel there is a need for them to ever
# set it, and even then we may just help them to append to a list.
pulp_irregularly_named_plugins:
  - galaxy-ng
pulp_django_admin_paths:
  - "{{ pulp_install_dir }}/bin/django-admin"
  - "{{ pulp_install_dir }}/bin/python3-django-admin"
pulp_pkg_name_prefix: "python3-"
pulp_pkg_pulpcore_name: "{{ pulp_pkg_name_prefix }}pulpcore"
pulp_pkg_repo:
pulp_pkg_undeclared_deps:
  - python3-psycopg2
  - pulpcore-selinux
  - python3-djangorestframework
  - python3-djangorestframework-queryfields
pulp_pkg_upgrade_all: false
pulp_upgraded_manually: false
# For Enterprise Linux distros, set the desired SELinux state.
# Set to one of the following values: 'enforcing', 'disabled', 'permissive'
pulp_selinux_mode: 'enforcing'
