---

pulp_cache_dir: '/var/lib/pulp/tmp'
pulp_config_dir: '/etc/pulp'
# This var intentionally not advertised to users, because there is no
# foreseeable need for them to change the filename, only pulp_config_dir.
pulp_settings_file: '{{ pulp_config_dir }}/settings.py'
pulp_install_source: pip
pulp_install_dir: '{{ (pulp_install_source == "packages") | ternary("/usr", "/usr/local/lib/pulp") }}'
__pulp_daemons_dir: '{{ (pulp_install_source == "packages") | ternary("/usr/libexec/pulpcore", pulp_install_dir ~ "/bin") }}'
pulp_install_api_service: true
# Deprecated unused. Variables for dependency upgrades are TBD
pulp_upgrade: false
pulp_user: pulp
pulp_user_id:
pulp_group: pulp
pulp_group_id:
pulp_user_home: '/var/lib/pulp'
__pulp_artifact_dir: "{{ pulp_user_home | regex_replace('\\/$', '')  }}/artifact"
pulp_pip_editable: yes
pulp_use_system_wide_pkgs: false
prereq_pip_packages:
  - Jinja2
pulp_rhel_codeready_repo:
  - codeready-builder-for-rhel-8-x86_64-rpms
  - rhui-codeready-builder-for-rhel-8-rhui-rpms
  - codeready-builder-for-rhel-8-rhui-rpms
rhel7_optional_repo:
  - rhui-rhel-7-server-rhui-optional-rpms
  - rhel-7-server-rhui-optional-rpms
  - rhel-7-server-optional-rpms
  - rhel-7-workstation-optional-rpms
epel_release_packages:
  - epel-release
  - "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_facts.distribution_major_version }}.noarch.rpm"
# The names of any pip packages that are plugins but do not begin with "pulp-"
# These are specified regardless of whether or not the user is installing it.
# We will advertise this to users once we feel there is a need for them to ever
# set it, and even then we may just help them to append to a list.
pulp_irregularly_named_plugins:
  - galaxy-ng
pulp_pkg_name_prefix: "python3-"
pulp_pkg_pulpcore_name: "{{ pulp_pkg_name_prefix }}pulpcore"
pulp_pkg_repo:
pulp_pkg_repo_gpgcheck: True
pulp_pkg_undeclared_deps:
  - python3-psycopg2
  - pulpcore-selinux
  - python3-djangorestframework
  - python3-djangorestframework-queryfields
pulp_pkg_upgrade_all: false
__pulp_pkg_repo_name: "pulpcore"
__pulp_pkg_repo_gpgkey: "{{ pulp_pkg_repo.rstrip('/') }}/../../GPG-RPM-KEY-pulpcore"
pulp_upgraded_manually: false

# The order is significant; linear order to handle the dependency tree
__pulp_selinux_policy_pkgs:
  - pulpcore_port
  - pulpcore
  - pulpcore_rhsmcertd
__pulp_selinux_repo: 'https://github.com/pulp/pulpcore-selinux.git'
__pulp_selinux_version: '1.2.3'
__pulp_selinux_label_dirs:
  - "{{ pulp_install_dir }}"
  - "{{ pulp_config_dir }}"
  - "{{ pulp_user_home }}"
__pulp_selinux_label_dirs_optional:
  # Depending on the roles applied yet whether or not Pulp is running, these may
  # not exist, throwing error code 255 when a called command realizes nothing
  # is present.
  - "/var/run/pulpcore*"
