---
pulp_preq_packages:
  - python3
  - python3-devel
  - python3-libselinux  # For ansible itself
  - gcc                 # For psycopg2
  - make                # For make docs, and SELinux policy install
  - libpq-devel         # Renamed/Split version of postgresql-devel
  - git                 # For source install, and SELinux policy install
  - sudo

# Pulp requires Python 3.6+.
pulp_python_interpreter: /usr/bin/python3
pulp_python_cryptography:
  - python3-cryptography
