---
# Intermediate var for pulp_install_plugins_normalized, based on this example;
# https://gist.github.com/kcem/5ec90b97c08fafd0397f248e8c31b25b
# With the to_json fix for Python2:
# https://stackoverflow.com/questions/41521138/ansible-template-adds-u-to-array-in-template
pulp_install_plugins_normalized_yml: |-
  {% for key, value in pulp_install_plugins.items() %}
  {{ key.replace('_', '-') }}: {{ value | to_json }}
  {% endfor %}
# A pulp_install_plugins but with the plugin names corrected:
# pip/PyPI only uses dashes, not underscores.
pulp_install_plugins_normalized: "{{ pulp_install_plugins_normalized_yml | from_yaml }}"
__pulp_common_pulp_pki_dir: "{{ pulp_config_dir }}/certs"
# Users should not set this variable, instead using `pulp_settings`
__pulp_common_pulp_settings_defaults:
  databases:
    default:
      HOST: localhost
      ENGINE: django.db.backends.postgresql_psycopg2
      NAME: pulp
      USER: pulp
      PASSWORD: pulp
  private_key_path: "{{ __pulp_common_pulp_pki_dir }}/token_private_key.pem"
  public_key_path: "{{ __pulp_common_pulp_pki_dir }}/token_public_key.pem"
  token_server: "https://{{ ansible_facts.fqdn }}/token"
  token_signature_algorithm: ES256
__pulp_common_merged_pulp_settings: "{{ __pulp_common_pulp_settings_defaults|combine(pulp_settings, recursive=True) }}"
