---
pulp_preq_packages:
  - python3
  - python3-dev
  - python3-venv
  - libpq-dev
  - gcc                 # For psycopg2
  - git                 # For source install
  - sudo
  - gpg                 # For the signing service via the gpg python module

# Pulp requires Python 3.6+.
pulp_python_interpreter: /usr/bin/python3
pulp_python_cryptography:
  - python3-cryptography
