---
# vars file for pulp_rpm_prerequisites on Debian
rpm_prereq_packages:
  - gcc
  - make
  - cmake
  - libbz2-dev
  - libcairo2-dev
  - libexpat1-dev
  - libmagic-dev
  - libglib2.0-dev
  - libgirepository1.0-dev
  - libcurl4-openssl-dev
  - libxml2-dev
  - libpython3-dev
  - librpm-dev
  - libssl-dev  # createrepo_c
  - libsqlite3-dev
  - liblzma-dev
  - libmodulemd-dev
  - libzck-dev
  - zlib1g-dev

# These packages must be explicitly installed during the pulp role, after the
# venv is created. Otherwise, older versions of pip that lack PEP517/PEP518
# support cannot use them to build createrepo_c or libcomps.
#
# Also note that the following replacement values do not work:
# - pip>=19<20
# - setuptools>=40.8<41
# Due to this issue:
# https://github.com/pypa/setuptools/issues/1694#issuecomment-466010982
rpm_prereq_pip_packages:
  - scikit-build
